name: Playwright Tests
env:
  ## Sets environment variables
  NETLIFY_SITE_NAME: "flavor-hive" # This is the "https://deploy-preview-1--${NETLIFY_SITE_NAME}.netlify.app"
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  tests_e2e_netlify_prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Wait for Netlify Deploy Preview
        run: |
          function waitForNetlifyDeployPreview() {
            local deploy_url="$NETLIFY_DEPLOY_URL"
            local retry_count=0
            local max_retries=5

            while true; do
              # Check deploy preview status
              netlify deploy:info --site $NETLIFY_SITE_ID --deploy $deploy_url
              if [[ $? -eq 0 ]]; then
                # Deploy preview is published
                echo "Deploy preview published successfully!"
                break
              elif [[ $retry_count -eq $max_retries ]]; then
                # Maximum retries reached, fail the job
                echo "Failed to wait for Netlify deploy preview after $max_retries attempts."
                exit 1
              fi

              # Retry after a delay with exponential backoff
              echo "Retrying in $(($retry_count * 2)) seconds..."
              sleep $(($retry_count * 2))
              retry_count=$((retry_count + 1))
            done
          }

          waitForNetlifyDeployPreview
  test:
    needs: tests_e2e_netlify_prepare
    name: Run end-to-end tests on Netlify PR preview
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      # Here we provide the preview domain, based on the GITHUB_PR_NUMBER combined with the NETLIFY_SITE_NAME
      env:
        PLAYWRIGHT_TEST_BASE_URL: "https://deploy-preview-${{env.GITHUB_PR_NUMBER}}--flavor-hive.netlify.app"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30