name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 12.x
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install
      run: |
        npm ci
    - name: Build
      run: |
        npm run build
    - name: Waiting for 200 from the Netlify Preview
      uses: kamranayub/wait-for-netlify-action@v2.1.0
      id: wait-for-netflify-preview
      with:
        site_name: "flavor-hive"
      env:
        NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        PLAYWRIGHT_TEST_BASE_URL: "${{ steps.wait-for-netflify-preview.outputs.url }}"
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
